version: "3.7"
services:
  ghidra-server:
    image: danigoland/ghidra-server-alpine:latest # you can change it to the local image if you wish
    container_name: ghidra-server-alpine
    volumes:
      - ./repos:/repos
    ports:
      - "13100-13102:13100-13102"